exclude: 'migrations.versions.*\.py$'
repos:
  - repo: git@github.com:ambv/black
    rev: stable
    hooks:
      - id: black
        args:
        - --skip-string-normalization
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: end-of-file-fixer
      #- id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        exclude: "tests.(utils|mocks).py$"
        args:
          - --django
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      #- id: detect-aws-credentials
      - id: mixed-line-ending
        args:
          - --fix=auto
      #- id: pretty-format-json
      #- id: sort-simple-yaml
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --ignore=E203,W503
  - repo: git@github.com:pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
      - id: autopep8
        args:
          - --max-line-length=120
          - --in-place
          - --aggressive
          - --aggressive
          - --ignore=E203,E721
  - repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.2
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]
  - repo: git@github.com:asottile/reorder_python_imports
    rev: v1.3.5
    hooks:
      - id: reorder-python-imports
        args:
          - --py37-plus
  - repo: git@github.com:myint/docformatter.git
    rev: v1.1
    hooks:
      - id: docformatter
        args:
          [
            "--in-place",
            "--wrap-summaries=80",
            "--wrap-descriptions=80",
            "--pre-summary-newline",
            "--make-summary-multi-line",
          ]
#  - repo: meta
#    hooks:
#      - id: check-hooks-apply
#      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: freeze-requirements
        name: Freeze Requirements
        files: 'none'
        entry: python ./tools/freeze-requirements.py
        language: system
        always_run: false
