version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing requirements"
      - pip install -r requirements.txt
  build:
    commands:
      - mv .env_template .env
      - pytest flask_rest_api/tests
      - sed -i '$ d' setup.cfg # exclude flask_rest_api from coverage report
      - coverage run -m pytest tests
      - coverage report
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION > version.txt
artifacts:
  files:
    - ".ebextensions/*"
    - "app/**/*"
    - "flask_rest_api/spec/**/*"
    - "flask_rest_api/*"
    - "requirements/**"
    - "migrations/**/*"
    - "templates/**/*"
    - "tools/**/*"
    - "application.py"
    - "config.py"
    - "logging-conf.yaml"
    - "requirements.txt"
    - "version.txt"
