"""adding complaint_status to Table Complaint

Revision ID: 1504d7706702
Revises: 8b7ea08206a8
Create Date: 2019-06-12 23:10:29.514947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1504d7706702'
down_revision = '8b7ea08206a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('complaint_status', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaint', 'complaint_status')
    # ### end Alembic commands ###
