"""drop Complaint Table

Revision ID: 1caea2fe0b66
Revises: d92d0bcf11d5
Create Date: 2019-06-07 13:01:34.184104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1caea2fe0b66'
down_revision = 'd92d0bcf11d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_complaint_complain_timestamp', table_name='complaint')
    op.drop_index('ix_complaint_purchase_timestamp', table_name='complaint')
    op.drop_index('ix_complaint_user_id', table_name='complaint')
    op.drop_table('complaint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('complaint_body', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('expected_solution_body', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('complain_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('complain_type', sa.VARCHAR(length=140), nullable=True),
    sa.Column('if_comm_by_merchant', sa.BOOLEAN(), nullable=True),
    sa.Column('if_public', sa.BOOLEAN(), nullable=True),
    sa.Column('if_media_report', sa.BOOLEAN(), nullable=True),
    sa.Column('item_price', sa.VARCHAR(length=200), nullable=True),
    sa.Column('item_model', sa.VARCHAR(length=200), nullable=True),
    sa.Column('purchase_timestamp', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('if_comm_by_merchant IN (0, 1)'),
    sa.CheckConstraint('if_media_report IN (0, 1)'),
    sa.CheckConstraint('if_public IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_complaint_user_id', 'complaint', ['user_id'], unique=False)
    op.create_index('ix_complaint_purchase_timestamp', 'complaint', ['purchase_timestamp'], unique=False)
    op.create_index('ix_complaint_complain_timestamp', 'complaint', ['complain_timestamp'], unique=False)
    # ### end Alembic commands ###
