"""users table

Revision ID: 43cfddfb753c
Revises: db2d3789039b
Create Date: 2019-05-18 23:44:02.875597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cfddfb753c'
down_revision = 'db2d3789039b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('if_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('minority', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('real_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('registered_date', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    op.drop_column('user', 'registered_date')
    op.drop_column('user', 'real_name')
    op.drop_column('user', 'minority')
    op.drop_column('user', 'if_verified')
    op.drop_column('user', 'account_active')
    # ### end Alembic commands ###
