"""Adding pageIndex in FuzzySearch Table

Revision ID: 52657c8f8652
Revises: 6a9dff75e096
Create Date: 2019-06-21 11:37:00.579570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52657c8f8652'
down_revision = '6a9dff75e096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuzzy_search_raw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pageIndex', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuzzy_search_raw', schema=None) as batch_op:
        batch_op.drop_column('pageIndex')

    # ### end Alembic commands ###
