"""Adding total_records in FuzzySearch Table

Revision ID: 795889b027d7
Revises: 52657c8f8652
Create Date: 2019-06-21 21:03:49.735498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795889b027d7'
down_revision = '52657c8f8652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuzzy_search_raw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalRecords', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuzzy_search_raw', schema=None) as batch_op:
        batch_op.drop_column('totalRecords')

    # ### end Alembic commands ###
