"""adding merchant_id field in table compalint

Revision ID: 8b7ea08206a8
Revises: 526870fd6eb2
Create Date: 2019-06-09 13:55:38.493872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7ea08206a8'
down_revision = '526870fd6eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_complaint_merchant_id'), 'complaint', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_merchant_id'), table_name='complaint')
    op.drop_column('complaint', 'merchant_id')
    # ### end Alembic commands ###
