"""change binary to string in MerchantRaw table

Revision ID: 9475155724bb
Revises: fd87cd1b7b12
Create Date: 2019-05-26 23:05:30.028201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9475155724bb'
down_revision = 'fd87cd1b7b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_raw_data', 'storage',
               existing_type=sa.BLOB(),
               type_=sa.String(length=10000),
               existing_nullable=True)
    op.alter_column('merchant_raw', 'storage',
               existing_type=sa.BLOB(),
               type_=sa.String(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_raw', 'storage',
               existing_type=sa.String(length=10000),
               type_=sa.BLOB(),
               existing_nullable=True)
    op.alter_column('company_raw_data', 'storage',
               existing_type=sa.String(length=10000),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
