"""drop a table

Revision ID: a98114a99a51
Revises: 9475155724bb
Create Date: 2019-05-26 23:15:34.106370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98114a99a51'
down_revision = '9475155724bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_raw_data')
    # op.alter_column('merchant_raw', 'storage',
    #            existing_type=sa.BLOB(),
    #            type_=sa.String(length=10000),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_raw', 'storage',
               existing_type=sa.String(length=10000),
               type_=sa.BLOB(),
               existing_nullable=True)
    op.create_table('company_raw_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('keyNo', sa.VARCHAR(length=140), nullable=True),
    sa.Column('storage', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
