"""adding merchant query raw table

Revision ID: c2b92d15058a
Revises: 2b93d36c8a59
Create Date: 2019-05-26 23:30:37.280347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b92d15058a'
down_revision = '2b93d36c8a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_query_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=140), nullable=True),
    sa.Column('storage', sa.String(length=20000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('keyword_to_companies')
    op.drop_table('merchant_raw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_raw',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=140), nullable=True),
    sa.Column('storage', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_to_companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=140), nullable=True),
    sa.Column('keyNoArray', sa.VARCHAR(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('merchant_query_raw')
    # ### end Alembic commands ###
