"""FuzzyQuery Table

Revision ID: d0d5c83f67d0
Revises: 43cfddfb753c
Create Date: 2019-05-21 14:41:52.938171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d5c83f67d0'
down_revision = '43cfddfb753c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=140), nullable=True),
    sa.Column('storage', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant_raw')
    # ### end Alembic commands ###
