"""KeywordToCompanies table

Revision ID: d0f083141176
Revises: d0d5c83f67d0
Create Date: 2019-05-25 23:24:35.816366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f083141176'
down_revision = 'd0d5c83f67d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_to_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=140), nullable=True),
    sa.Column('keyNoArray', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_to_companies')
    # ### end Alembic commands ###
