"""adding Complaint table

Revision ID: d92d0bcf11d5
Revises: c2b92d15058a
Create Date: 2019-05-28 15:03:16.198572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92d0bcf11d5'
down_revision = 'c2b92d15058a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_body', sa.String(length=2000), nullable=True),
    sa.Column('expected_solution_body', sa.String(length=2000), nullable=True),
    sa.Column('complain_timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('complain_type', sa.String(length=140), nullable=True),
    sa.Column('if_comm_by_merchant', sa.Boolean(), nullable=True),
    sa.Column('if_public', sa.Boolean(), nullable=True),
    sa.Column('if_media_report', sa.Boolean(), nullable=True),
    sa.Column('item_price', sa.String(length=200), nullable=True),
    sa.Column('item_model', sa.String(length=200), nullable=True),
    sa.Column('purchase_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_complain_timestamp'), 'complaint', ['complain_timestamp'], unique=False)
    op.create_index(op.f('ix_complaint_purchase_timestamp'), 'complaint', ['purchase_timestamp'], unique=False)
    op.create_index(op.f('ix_complaint_user_id'), 'complaint', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_user_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_purchase_timestamp'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_complain_timestamp'), table_name='complaint')
    op.drop_table('complaint')
    # ### end Alembic commands ###
