"""new CompanyRawData table

Revision ID: fd87cd1b7b12
Revises: d0f083141176
Create Date: 2019-05-25 23:51:23.734422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd87cd1b7b12'
down_revision = 'd0f083141176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyNo', sa.String(length=140), nullable=True),
    sa.Column('storage', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_raw_data')
    # ### end Alembic commands ###
